In [1]:
import numpy as np
import pandas as pd

In [2]:
date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

In [3]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [4]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [5]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [6]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

Working With Dates

In [7]:
# Converting to datetype datatype
date['date'] = pd.to_datetime(date['date'])

In [8]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

1.Extract Year

In [10]:
date['date_year'] = date['date'].dt.year
date.sample(5)

          date  product_id  city_id  orders  date_year
440 2018-10-31        4382       23       5       2018
38  2019-02-15        7025       14      33       2019
398 2019-07-19        2307        4       9       2019
91  2018-09-18         923       13       1       2018
505 2019-12-12        2585       25       1       2019

2.Extract Month

In [12]:
date['date_month_no'] = date['date'].dt.month
date.sample(5)

          date  product_id  city_id  orders  date_year  date_month_no
36  2018-07-13        3432       13      28       2018              7
44  2018-08-03         803       23       9       2018              8
869 2018-12-30        2542        0       2       2018             12
727 2019-10-20        1932       18       6       2019             10
947 2019-11-17          88       24      13       2019             11

In [14]:
date['date_month_name'] = date['date'].dt.month_name()
date.sample(5)

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name
277,2018-11-21,2017,11,3,2018,11,November
265,2019-04-28,2850,16,6,2019,4,April
183,2019-02-08,4785,14,4,2019,2,February
304,2018-09-15,438,22,12,2018,9,September
61,2018-07-20,7025,14,22,2018,7,July

3.Extract Days

In [16]:
date['date_day'] = date['date'].dt.day
date.sample(5)

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day
345,2018-07-26,6857,18,61,2018,7,July,26
156,2019-04-25,568,8,25,2019,4,April,25
636,2018-11-01,1744,13,4,2018,11,November,1
305,2019-07-05,25,18,1,2019,7,July,5
302,2018-10-05,2012,8,32,2018,10,October,5

In [18]:
# Day of week
date['date_day_of_week'] = date['date'].dt.dayofweek
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_day_of_week
0,2019-12-10,5628,25,3,2019,12,December,10,1
1,2018-08-15,3646,14,157,2018,8,August,15,2
2,2018-10-23,1859,25,1,2018,10,October,23,1
3,2019-08-17,7292,25,1,2019,8,August,17,5
4,2019-01-06,4344,25,3,2019,1,January,6,6

In [20]:
# DAy of week_ name
date['date_day_of_week_name'] = date['date'].dt.day_name()
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_day_of_week,date_day_of_week_name
0,2019-12-10,2019,12,December,10,1,Tuesday
1,2018-08-15,2018,8,August,15,2,Wednesday
2,2018-10-23,2018,10,October,23,1,Tuesday
3,2019-08-17,2019,8,August,17,5,Saturday
4,2019-01-06,2019,1,January,6,6,Sunday

In [22]:
# Is Weekend ?
date['date_is_weekend'] = np.where(date['date_day_of_week_name'].isin(['Sunday','Saturday']),1,0)
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_day_of_week,date_day_of_week_name,date_is_weekend
0,2019-12-10,2019,12,December,10,1,Tuesday,0
1,2018-08-15,2018,8,August,15,2,Wednesday,0
2,2018-10-23,2018,10,October,23,1,Tuesday,0
3,2019-08-17,2019,8,August,17,5,Saturday,1
4,2019-01-06,2019,1,January,6,6,Sunday,1

4.Extract Week of the Year

In [24]:
date['date_week'] = date['date'].dt.isocalendar().week
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_day_of_week,date_day_of_week_name,date_is_weekend,date_week
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43
3,2019-08-17,2019,8,August,17,5,Saturday,1,33
4,2019-01-06,2019,1,January,6,6,Sunday,1,1

5.Extract Quarter

In [25]:
date['quarter'] = date['date'].dt.quarter
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_day_of_week,date_day_of_week_name,date_is_weekend,date_week,quarter
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50,4
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33,3
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43,4
3,2019-08-17,2019,8,August,17,5,Saturday,1,33,3
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1

6.Extract Semester

In [27]:
date['semester'] = np.where(date['quarter'].isin([1,2]),1,2)
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_day_of_week,date_day_of_week_name,date_is_weekend,date_week,quarter,semester
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50,4,2
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33,3,2
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43,4,2
3,2019-08-17,2019,8,August,17,5,Saturday,1,33,3,2
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1,1

7.Extract Time elapsed between dates

In [28]:
import datetime
today = datetime.datetime.today()
today

datetime.datetime(2025, 4, 12, 14, 44, 33, 2388)

In [29]:
today - date['date']

0     1950 days 14:44:33.002388
1     2432 days 14:44:33.002388
2     2363 days 14:44:33.002388
3     2065 days 14:44:33.002388
4     2288 days 14:44:33.002388
                 ...
995   2378 days 14:44:33.002388
996   2319 days 14:44:33.002388
997   2167 days 14:44:33.002388
998   2232 days 14:44:33.002388
999   2006 days 14:44:33.002388
Name: date, Length: 1000, dtype: timedelta64[ns]

In [31]:
(today - date['date']).dt.days

0      1950
1      2432
2      2363
3      2065
4      2288
       ...
995    2378
996    2319
997    2167
998    2232
999    2006
Name: date, Length: 1000, dtype: int64

In [35]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [36]:
# Converting to datetime datatype
time['date'] = pd.to_datetime(time['date'])

In [37]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [39]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second
time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

Extact Time

In [41]:
time['time'] = time['date'].dt.time
time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

Time Difference

In [42]:
today - time['date']

0     4136 days 13:54:33.002388
1     4000 days 15:04:33.002388
2     4486 days 14:23:33.002388
3     3788 days 14:13:33.002388
4     4185 days 15:33:33.002388
                 ...
995   4775 days 13:54:33.002388
996   4096 days 15:30:33.002388
997   4561 days 15:07:33.002388
998   4677 days 15:10:33.002388
999   3949 days 15:19:33.002388
Name: date, Length: 1000, dtype: timedelta64[ns]

In [43]:
# In second
(today - time['date']) / np.timedelta64(1,'s')

0      3.574005e+08
1      3.456543e+08
2      3.876422e+08
3      3.273344e+08
4      3.616400e+08
           ...
995    4.126101e+08
996    3.539502e+08
997    3.941249e+08
998    4.041474e+08
999    3.412488e+08
Name: date, Length: 1000, dtype: float64

In [44]:
# In Mintue
(today - time['date']) / np.timedelta64(1,'m')

0      5.956675e+06
1      5.760905e+06
2      6.460704e+06
3      5.455574e+06
4      6.027334e+06
           ...
995    6.876835e+06
996    5.899171e+06
997    6.568748e+06
998    6.735791e+06
999    5.687480e+06
Name: date, Length: 1000, dtype: float64

In [45]:
# In Hours
(today - time['date']) / np.timedelta64(1,'h')

0       99277.909167
1       96015.075834
2      107678.392501
3       90926.225834
4      100455.559167
           ...
995    114613.909167
996     98319.509167
997    109479.125834
998    112263.175834
999     94791.325834
Name: date, Length: 1000, dtype: float64